# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2025-02-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid

def generate_unique_tracking_tokens(apps, schema_editor):
    """
    Генерирует уникальные tracking_token для всех существующих Subscriber.
    """
    Subscriber = apps.get_model("mailer", "Subscriber")
    for subscriber in Subscriber.objects.all():
        subscriber.tracking_token = uuid.uuid4() # Используем uuid.uuid4() для UUIDField
        subscriber.save(update_fields=['tracking_token']) # Важно указать update_fields

class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_auto_20250213_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOpenTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='mailer.Mailing')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='tracking_token',
            field=models.UUIDField(unique=False, default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(generate_unique_tracking_tokens, migrations.RunPython.noop),  # Генерация UUIDs
        migrations.AlterField(
            model_name='subscriber',
            name='tracking_token',
            field=models.UUIDField(unique=True, editable=False),  # unique=True на втором этапе
        ),
        migrations.AddField(
            model_name='emailopentracking',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opens', to='mailer.Subscriber'),
        ),
    ]
